package uniandes.dpoo.galeria.interfaz;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.WindowConstants;

import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author user
 */
public class FormLogin extends JPanel {
	
	private JButton signUp;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel createAccount;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel panelBienvenida;
    private JPasswordField jPasswordField1;
    private JTextField campoUsername;
    private ActionListener listener;
    /**
     * Creates new form NewJFrame
     */
    public FormLogin(ActionListener listener) {
    	this.listener = listener;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	panelBienvenida = new javax.swing.JPanel();
        jLabel1 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel9 = new JLabel();
        jLabel2 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        campoUsername = new JTextField();
        jLabel6 = new JLabel();
        signUp = new JButton();
        createAccount = new JLabel();
        jPasswordField1 = new JPasswordField();

        this.setLayout(new AbsoluteLayout());

        panelBienvenida.setBackground(new java.awt.Color(0, 102, 153));
        panelBienvenida.setLayout(new AbsoluteLayout());

        jLabel1.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel1.setIcon(new ImageIcon(getClass().getResource("/IMG/2763138.png"))); // NOI18N
        jLabel1.setToolTipText("Exit");
        jLabel1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel1.setPreferredSize(new Dimension(512, 512));
        panelBienvenida.add(jLabel1, new AbsoluteConstraints(0, 0, 40, 40));

        jLabel4.setFont(new Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel4.setText("A la Galeria Da Vinci");
        panelBienvenida.add(jLabel4, new AbsoluteConstraints(0, 300, 350, -1));

        jLabel5.setFont(new Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel5.setForeground(new Color(51, 204, 255));
        jLabel5.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel5.setText("Bienvenidos");
        panelBienvenida.add(jLabel5, new AbsoluteConstraints(0, 250, 350, -1));

        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel9.setIcon(new ImageIcon(getClass().getResource("/IMG/4201213.png"))); // NOI18N
        jLabel9.setPreferredSize(new Dimension(512, 512));
        panelBienvenida.add(jLabel9, new AbsoluteConstraints(0, 90, 350, 160));

        this.add(panelBienvenida, new AbsoluteConstraints(0, 0, 350, 420));

        jLabel2.setFont(new Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setText("Galeria Da Vinci Login");
        this.add(jLabel2, new AbsoluteConstraints(370, 50, -1, -1));

        jLabel7.setFont(new Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel7.setForeground(new Color(153, 153, 153));
        jLabel7.setText("Ingresa tu usuario");
        this.add(jLabel7, new AbsoluteConstraints(370, 90, -1, -1));

        jLabel8.setFont(new Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel8.setForeground(new Color(153, 153, 153));
        jLabel8.setText("Username");
        this.add(jLabel8, new AbsoluteConstraints(370, 140, -1, -1));

        campoUsername.setText("Enter Username");
        campoUsername.setBorder(BorderFactory.createLineBorder(new Color(153, 153, 153)));
        campoUsername.setName(""); // NOI18N
        campoUsername.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        this.add(campoUsername, new AbsoluteConstraints(370, 170, 300, 40));

        jLabel6.setFont(new Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel6.setForeground(new Color(153, 153, 153));
        jLabel6.setText("Password");
        this.add(jLabel6, new AbsoluteConstraints(370, 240, -1, -1));

        signUp.setBackground(new Color(0, 153, 0));
        signUp.setFont(new Font("Segoe UI Semibold", 0, 18)); // NOI18N
        signUp.setForeground(new Color(255, 255, 255));
        signUp.setLabel("Login");
        
        signUp.setActionCommand("COMPRADOR");
        signUp.addActionListener(listener);
        
        this.add(signUp, new AbsoluteConstraints(370, 350, 120, 50));

        createAccount.setFont(new Font("Segoe UI Semibold", 0, 14)); // NOI18N
        createAccount.setForeground(new Color(0, 153, 204));
        createAccount.setHorizontalAlignment(SwingConstants.CENTER);
        createAccount.setText("Create Account");
        createAccount.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.add(createAccount, new AbsoluteConstraints(640, 0, -1, -1));
        //cambiar a boton

        jPasswordField1.setText("Enter Password");
        jPasswordField1.setBorder(BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPasswordField1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        this.add(jPasswordField1, new AbsoluteConstraints(370, 270, 310, 40));

       
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton2ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jPasswordField1ActionPerformed(ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    
}
